import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { LucideAngularModule, Activity, AlertCircle, AlertTriangle, ArrowLeft, ArrowRight, ArrowUp, BarChart3, Bell, BookOpen, Briefcase, Building, Building2, Calendar, Check, CheckCircle, ChevronDown, ChevronRight, ChevronUp, Circle, Clock, Code, Copy, CreditCard, Database, DollarSign, Edit, Eye, EyeOff, FilePlus, FileText, Filter, Flag, Folder, FolderOpen, FolderTree, FunctionSquare, GitBranch, Glasses, HandMetal, History, Home, Inbox, Info, Key, LayoutDashboard, List, Loader, Mail, Map, MapPin, MessageSquare, Moon, Package, Phone, PhoneCall, PhoneIncoming, PhoneOff, Plus, PlusCircle, Rocket, Save, Search, SearchX, Settings, Shield, ShieldBan, ShieldCheck, ShieldOff, ShoppingCart, Smile, Sparkles, Star, Sun, Table, Table2, Tag, Trash2, TrendingUp, Type, User, UserCircle, UserCog, Users, UserX, Wallet, X, XCircle, Zap } from 'lucide-angular';

import { routes } from './app.routes';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptorsFromDi()),
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        AlertCircle,
        AlertTriangle,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        BarChart3,
        Bell,
        BookOpen,
        Briefcase,
        Building,
        Building2,
        Calendar,
        Check,
        CheckCircle,
        ChevronDown,
        ChevronRight,
        ChevronUp,
        Circle,
        Clock,
        Code,
        Copy,
        CreditCard,
        Database,
        DollarSign,
        Edit,
        Eye,
        EyeOff,
        FilePlus,
        FileText,
        Filter,
        Flag,
        Folder,
        FolderOpen,
        FolderTree,
        FunctionSquare,
        GitBranch,
        Glasses,
        HandMetal,
        History,
        Home,
        Inbox,
        Info,
        Key,
        LayoutDashboard,
        List,
        Loader,
        Mail,
        Map,
        MapPin,
        MessageSquare,
        Moon,
        Package,
        Phone,
        PhoneCall,
        PhoneIncoming,
        PhoneOff,
        Plus,
        PlusCircle,
        Rocket,
        Save,
        Search,
        SearchX,
        Settings,
        Shield,
        ShieldBan,
        ShieldCheck,
        ShieldOff,
        ShoppingCart,
        Smile,
        Sparkles,
        Star,
        Sun,
        Table,
        Table2,
        Tag,
        Trash2,
        TrendingUp,
        Type,
        User,
        UserCircle,
        UserCog,
        Users,
        UserX,
        Wallet,
        X,
        XCircle,
        Zap
      })
    )
  ]
};
